import random  # Imports the random module for generating random values

# Stores all applicants generated by the program
applicants = []

# List of possible applicant names
names = [
    'Jamal', 'Sarah', 'David', 'Emily', 'Aisha',
    'Michael', 'Sophia', 'Daniel', 'Olivia', 'Noah',
    'Ali bin Rahman', 'Aisyah binte Ahmad',
    'Kumar S/O Raj', 'John D/O Tan'
]

# ==================================================
# GENERATE APPLICANTS
# ==================================================
def generate_applicants():

    # Randomly choose 10 names from the list
    selected_names = random.sample(names, 10)

    # Create an applicant for each selected name
    for name in selected_names:

        # Add applicant information into the applicants list
        applicants.append({

            # Applicant's name
            'name': name,

            # Random experience score between 1 and 10
            'experience': random.randint(1, 10),

            # Random skills score between 1 and 10
            'skills': random.randint(1, 10)
        })

# ==================================================
# SHOW ORIGINAL UNBIASED RANKINGS
# ==================================================
def original_ranking():

    # Create a new list to store unbiased rankings
    original_applicants = []

    # Calculate scores without bias
    for applicant in applicants:

        # Total score is experience + skills
        score = (
            applicant['experience']
            + applicant['skills']
        )

        # Store applicant information and score
        original_applicants.append({
            'name': applicant['name'],
            'experience': applicant['experience'],
            'skills': applicant['skills'],
            'score': score
        })

    # Sort applicants from highest score to lowest score
    original_applicants.sort(
        key=lambda x: x['score'],
        reverse=True
    )

    print("\n=== ORIGINAL UNBIASED RANKINGS ===")

    # Display ranking list
    for rank, applicant in enumerate(original_applicants, start=1):

        print(
            f"{rank}. {applicant['name']} | "
            f"Experience: {applicant['experience']} | "
            f"Skills: {applicant['skills']} | "
            f"Score: {applicant['score']}"
        )

# ==================================================
# APPLY BIAS TO CERTAIN NAMES
# ==================================================
def apply_bias():

    # Loop through every applicant
    for applicant in applicants:

        # Convert name to lowercase for easier comparison
        name = applicant['name'].lower()

        # Start with original score
        score = (
            applicant['experience']
            + applicant['skills']
        )

        # Simulated bias:
        # If the applicant is Jamal, subtract 5 points
        if name == 'jamal':
            score -= 5

        # Simulated bias:
        # If name contains certain identifiers,
        # subtract another 5 points
        if any(x in name for x in ['d/o', 's/o', 'bin', 'binte']):
            score -= 5

        # Save biased score
        applicant['score'] = score

# ==================================================
# SORT APPLICANTS AFTER BIAS IS APPLIED
# ==================================================
def sort_biased():

    # Sort applicants based on biased score
    applicants.sort(
        key=lambda x: x['score'],
        reverse=True
    )

    print("\n=== BIASED RANKINGS ===")

    # Display biased rankings
    for rank, applicant in enumerate(applicants, start=1):

        print(
            f"{rank}. {applicant['name']} | "
            f"Experience: {applicant['experience']} | "
            f"Skills: {applicant['skills']} | "
            f"Score: {applicant['score']}"
        )

# ==================================================
# DETECT BIAS IN HIRING RESULTS
# ==================================================
def detect_bias():

    # Assume only the top 5 applicants are hired
    hired = applicants[:5]

    # Counters for each group
    group_A = 0
    group_B = 0

    # Check each hired applicant
    for applicant in hired:

        name = applicant['name'].lower()

        # Group B contains applicants affected by bias
        if (
            name == 'jamal'
            or any(x in name for x in ['d/o', 's/o', 'bin', 'binte'])
        ):
            group_B += 1

        # Everyone else belongs to Group A
        else:
            group_A += 1

    print("\n=== BIAS DETECTION ===")

    print("Group A hired:", group_A)
    print("Group B hired:", group_B)

    # Compare hiring outcomes
    if group_A > group_B:
        print("Possible bias against Group B")

    elif group_B > group_A:
        print("Possible bias against Group A")

    else:
        print("No bias detected")

# ==================================================
# FAIRNESS CORRECTION (BLIND RECRUITMENT)
# ==================================================
def fairness_correction():

    # Create a new list for corrected rankings
    corrected_applicants = []

    # Recalculate scores without any penalties
    for applicant in applicants:

        fair_score = (
            applicant['experience']
            + applicant['skills']
        )

        corrected_applicants.append({
            'name': applicant['name'],
            'experience': applicant['experience'],
            'skills': applicant['skills'],
            'score': fair_score
        })

    # Sort using fair scores only
    corrected_applicants.sort(
        key=lambda x: x['score'],
        reverse=True
    )

    print("\n=== FAIR RANKINGS (NAMES IGNORED) ===")

    # Display corrected rankings
    for rank, applicant in enumerate(corrected_applicants, start=1):

        print(
            f"{rank}. {applicant['name']} | "
            f"Experience: {applicant['experience']} | "
            f"Skills: {applicant['skills']} | "
            f"Score: {applicant['score']}"
        )

    # Top 5 hires after correction
    fair_hired = corrected_applicants[:5]

    group_A = 0
    group_B = 0

    # Count hires in each group again
    for applicant in fair_hired:

        name = applicant['name'].lower()

        if (
            name == 'jamal'
            or any(x in name for x in ['d/o', 's/o', 'bin', 'binte'])
        ):
            group_B += 1
        else:
            group_A += 1

    print("\n=== AFTER FAIRNESS CORRECTION ===")

    print("Group A hired:", group_A)
    print("Group B hired:", group_B)

    # Recommendation for reducing bias
    print("\nRecommendation:")
    print("Use blind recruitment.")
    print("Evaluate only qualifications, not names.")

# ==================================================
# MAIN PROGRAM
# ==================================================

# Step 1: Generate applicants
generate_applicants()

# Step 2: Show rankings before bias
original_ranking()

# Step 3: Apply bias to certain applicants
apply_bias()

# Step 4: Show rankings after bias
sort_biased()

# Step 5: Detect whether bias affected hiring outcomes
detect_bias()

# Step 6: Remove bias and compare results
fairness_correction()